### ISSUE TITLE
InlineKeyboardMarkup and InlineKeyboardButton

### ISSUE THREAD

**Issue by lippol94** [rubenlagus/TelegramBots#34] opened 2016-04-16 16:55 UTC
Greetings. Today I was starting to play around with InlineKeyboardMarkup type, so I supposed it should have been working like ReplyKeyboardMarkup (according to [Telegram APIs](https://core.telegram.org/bots/api#inlinekeyboardmarkup))
Although the `add` method takes a `List<List<String>>` as parameter instead of a `List<List<InlineKeyboadButton>>` or a consistent `List<InlineKeyboardRows>`.

I'm I missing something? Thank you.

**Comment by rubenlagus** [comment] 2016-04-17 09:56
Hi @lippol94, you are right it should be a `List<KeyboardRow>`, will try to fix as soon as I have a moment.

**Comment by lippol94** [comment] 2016-04-17 12:48
Nice! Thank you so much! :)

**Comment by rubenlagus** [comment] 2016-04-17 15:47
Should be fixed with Merge #38 

Finally I didn't added an InlineKeyboardRow object because for this case, the list can only be built by InlineKeyboardButtons, I added the KeyboardRow to keep compatibility for  old `List<List<string>>`

**Closed by rubenlagus** 2016-04-17 15:47 UTC
Labels: bug

**Comment by lippol94** [comment] 2016-04-18 07:13
Super! Thanks 😉

**Comment by danielgarciasantos** [comment] 2016-04-23 00:09
I can not reproduce the type InlineKeyboardMarkup and Inline Keyboard Button.
I would like to play a button inline control, could help me.
Thank you.

**Comment by maystrovoy** [comment] 2016-06-30 12:53
Hi, i having a problem with the Cyrillic text in InlineKeyboardButton.
When i tried:
`button.setText("Русский язык");`
as the result will be button with "??????? ????" text.
I tried to change the encoding (UTF-8) - gave no results.
Someone can verify or give advice
