### ISSUE TITLE
Listing commands with /{nameOfTheCommand}

### ISSUE THREAD

**Issue by GhsVilela** [rubenlagus/TelegramBots#436] opened 2018-04-16 19:12 UTC
I want to type /commands and then it return the message like this:

![captura de tela de 2018-04-16 16-10-46](https://user-images.githubusercontent.com/13207060/38829884-e444da68-4190-11e8-97da-cee11626f665.png)

with the /

**Comment by bvn13** [comment] 2018-04-17 08:51
it is implemented in ability bot. use it.

**Comment by GhsVilela** [comment] 2018-04-17 11:42
yes there is a command called commands that use the ability function inside AbilityBot class but it list the commands without the /

**Comment by AhabHyde** [comment] 2018-04-20 13:45
You have to use BotFather, you can set which commands the bot accepts and the description of every one of it

**Comment by GhsVilela** [comment] 2018-04-27 14:25
i don't think any of you guys understood what i want but ok. I wanna use the API in Java, there is nothing related to bot father.

**Comment by AhabHyde** [comment] 2018-04-27 14:29
I think you have to implement it yourself then, using the normal sendMessage and building your own message

**Comment by GhsVilela** [comment] 2018-04-27 21:00
For what i have tested the Abilities API recognize every method with
`public Ability nameOfTheCommand` as a command and if you type /commands it list all commands in your java code but it list the commands without the /.

**Comment by AzZureman** [comment] 2018-05-07 11:04
> The function that list the commands is native of abilities API

Ahah. @GhsVilela, native functions are functions such as java.lang.Object.hashCode(). If you dive into the sources you will see something like ``` public native int hashCode(); ``` without any implementations, and this is a real native function.
And [the function that list the commands](https://github.com/rubenlagus/TelegramBots/blob/431d94548647ee945d46bad09ee8443bab3d91c3/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/AbilityBot.java#L293-L314) (```public Ability reportCommands()```) even has a `public` access modifier! So, you just can `@Override` it with your own implementation.
But, you can't override this with any working solutions, because you must have access to `Map<String, Ability> abilities` [L119](https://github.com/rubenlagus/TelegramBots/blob/431d94548647ee945d46bad09ee8443bab3d91c3/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/AbilityBot.java#L119) from your extended class.

Since this point the issue is start.

@rubenlagus 
So, there are two ways to solve this issue:
1. Change access modifier of `Map<String, Ability> abilities` from `private` to `protected`
AzZureman/TelegramBots@faf4885bb8dc1a8104ac1ef229dc1ed9cc311c66
That will provide access to override `public Ability reportCommands()` method.

2. Put the `format` function in a separate method with `protected` access modifier
AzZureman/TelegramBots@b8b06f1d1d98fe109befc27aa23902a20b41393c
That will provide an opportunity to change the command's output line. For example: 
```java
    @Override
    public String formatCommandReport(String name, String info) {
        return format("/%s  - %s", name, info);
    }
```

**Comment by AzZureman** [comment] 2018-05-07 12:07
I think the first option from my suggestion is preferable, because it will give opportunity to filter output based on user privileges or may be something more intresting =)

**Comment by GhsVilela** [comment] 2018-05-07 21:15
Thanks, you saved me haha. I will try to do that these days, if i have any problems I'll comment here again.

**Comment by addo37** [comment] 2018-05-07 21:45
Hey there everyone. Since a few have weighed in and I'm the creator/maintainer of the AbilityBot module, I figured I'll give my 2 cents on this one.

The original intent of the /commands ability method is to immediately update the commands reported by Telegram by forwarding the message result. That is, if you update/add/remove an ability, forwarding the results of /commands to BotFather would sync the commands that users see when they prompt the bot via the slash character. BotFather requires the format to be:
command1  - info1
command2 - info2

Adding a slash would invalidate the commands abilities and its original purpose. Thank you for the proposed solutions @AzZureman, here's my feedback.

> Change access modifier of Map<String, Ability> abilities from private to protected. That will provide access to override public Ability reportCommands() method.
This map is very sensitive as it is used and referenced every time an update is ingested. While changing the access modifier would allow for a broader flexibility, it also means less security since the map structure at this stage is mutable. 

> Put the format function in a separate method with protected access modifier. That will provide an opportunity to change the command's output line. For example:
This is a neat solution. If this solution is implemented solely, then the user will be bound to use /commands for the formatted report. It does solve the issue of having the reporting format modifiable, but it doesn't extend the functionality.

The ideal solution is to add a public formatting method that is "overridable" and have the abilities map become protected and immutable. This way we allow the user to look at the content, add some other unique abilities that might require this visibility, but restrict any privilege to sabotage the ability registry.

**Comment by addo37** [comment] 2018-05-23 23:05
Thank you all for your suggestions. A PR has been initiated. You can view it at #466.

**Comment by GhsVilela** [comment] 2018-06-04 16:48
when i'll be able to use those changes?

**Comment by addo37** [comment] 2018-06-05 01:01
On next release, @GhsVilela. It has been merged.

**Closed** 2018-07-26 23:52 UTC
Labels: Abilities
