### ISSUE TITLE
Find links in message

### ISSUE THREAD

**Issue by sintaklaas** [rubenlagus/TelegramBots#613] opened 2019-05-11 20:39 UTC
Currently when i use:

`update.getMessage().getText()`

Its the raw text of message that has been sent.
But the message can cotnain links, how do i extract them from the text?

**Comment by Philipinho** [comment] 2019-05-11 21:33
It can be achieved using REGEX.

**Comment by sintaklaas** [comment] 2019-05-11 21:41
I cannot use REGEX cause when I send the bot this:

This is a link (http://www.google.com/)!

It doesnt have the http-link in it...
It just sees:

This is a link!

(with the clickable "link")

**Comment by gekoramy** [comment] 2019-05-12 22:10
https://core.telegram.org/bots/api#messageentity

**Comment by Chase22** [comment] 2019-07-18 13:10
@sintaklaas Please close this if the issue is resolved

**Closed** 2019-08-05 20:59 UTC
